### ISSUE TITLE
How do i get   %d/%m - %H:%M:%S   from the pibooth.cfg

### ISSUE THREAD

**Issue by DJ-Dingo** [DJ-Dingo/pibooth-lcd-I2c#4]
Hi @werdeil I am trying to get date/time from the pibooth.cfg  -  %d/%m - %H:%M:%S 

app.show_date_time = cfg.get('LCD_I2C', 'lcd_show_date_time').strip('"')
app.lcd.write_string('%s' % time.strftime('%s' % app.show_date_time))

But getting this error
File "/usr/lib/python3.7/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%d/%m - %H:%M:%S'

**Comment by DJ-Dingo** [comment]
Found a sulution for my problem, but still like to know how i can use % in the config.cfg

**Comment by werdeil** [comment]
Wow didn't see all the changes you made, nice! 

I'll work on the "%" not possible on the config, but in the meantime on the line:
``` app.lcd.write_string('%s' % time.strftime('%s' % app.show_date_time)) ```
Does it work if you put:
``` app.lcd.write_string(time.strftime(app.show_date_time))```

?

**Comment by DJ-Dingo** [comment]
Thx.

Don't think so, as it have problem using % in config.cfg. But i can try.
If i use %%d/%%m - %%H:%%M:%%S it should work, but not the normal way to do it. (trying that too)

Right now i changed it to use (d):(m) instead of %d:%m and then replace '(' with '%' and removing ')' in string.
Just to make it easy for the user.

But i like if i can use the normal Date-Time Format Codes %d/%m - %H:%M:%S - since that is standard. 
That way most users will be able to understand it. If they need to change the way date-time looks in the display.

**Comment by werdeil** [comment]
There is an issue with the % in the config, and the workaround is to use %% instead.

I also prefer to keep standard time formatting in the config instead of specific one with '('. 

My proposal here is more a python improvement: each time you have put ```som_function('%s' % something)```it is directly equivalent to ```some_function(something)``` and easier to read.

**Comment by DJ-Dingo** [comment]
I tried app.lcd.write_string(time.strftime(app.show_date_time)), and yes it does the same
I will make changes to that, next time i clean up. 

I allso tried the double %    -    %%d/%%m - %%H:%%M:%%S 
Works. BUT, only 1 time. If you go to menu, and back, where it generate the configuration file , it will then remove 1 % for every %% there is.  So  -  %%d/%%m - %%H:%%M:%%S   will become  %d/%m - %H:%M:%S
and next time you run pibooth it just crashes again.

So i have to use my () version until there are changes in the ConfigParser.

**Comment by DJ-Dingo** [comment]
Wont work with app.lcd.write_string(" " app.count.taken)
so i will keep them where count. is  app.lcd.write_string(" "'%s' % app.count.taken)

**Comment by DJ-Dingo** [comment]
hi @werdeil Working fine now with Date/Time :-)
