### ISSUE TITLE
Time stops running, in some states.

### ISSUE THREAD

**Issue by DJ-Dingo** [DJ-Dingo/pibooth-lcd-I2c#5]
Hi @werdeil, think this is the last thing to resolved, everything else is running perfect.

Time stopping in some states. (you can see seconds stops under these states).
For what i can see it is under "preview (countdown)" and "processing".
I dont have a printer so can't check if it also does it there.

**Comment by werdeil** [comment]
Can you provide a video of this so I can clearly see what is happening on the lcd?

**Comment by DJ-Dingo** [comment]
Yes, i try. Do you want to see both the screen and lcd, or just the lcd?

**Comment by DJ-Dingo** [comment]
@werdeil  
if you have sound on, you can hear pibooth-sound-effects in the background

[pibooth_lcd (convert-video-online.com).mov.zip](https://github.com/DJ-Dingo/pibooth-lcd-I2c/files/5482881/pibooth_lcd.convert-video-online.com.mov.zip)

**Comment by werdeil** [comment]
The states were the time freeze are states were the pibooth core code is doing something (not just waiting in loops). As the plugin are called before/after the core code it may happen.

One idea would be to launch the write_date part in another thread, but it may be overkill and I'm not sure that we can access to the same lcd object in 2 threads (or even the same port).

**Comment by DJ-Dingo** [comment]
Okay.  And the seconds is not that important and the counters work as they should. Also, no one is looking at the LCD while taking photos. 

We should be able to access lcd object in 2 threads and on the same port, but like you said it may be overkill.
My friend said there is another way to write to the LCD. If he sends something that makes sense, I can open again.
Otherwise we just let it be with the time/sec as it is. :-)
